### ISSUE TITLE
No longer works with @types/joi @14.3.3

### ISSUE THREAD

**Issue by onionhammer** [TCMiranda/joi-extract-type#15]
Upgraded @types/joi to 14.3.3 and suddenly I'm getting lots of these

> SomeFile.ts:46:41 - error TS2694: Namespace '".../node_modules/@types/joi/index"' has no exported member 'extractType'.

(Updated w/ narrowed down issue)

**Comment by TCMiranda** [comment]
Please upgrade to @15.0.0
