### PR TITLE
Update joi dependency to @hapi/joi@15.x for @hapi/hapi@18.x compatibility. Fixes #15

### LINKED ISSUE #15: No longer works with @types/joi @14.3.3
Upgraded @types/joi to 14.3.3 and suddenly I'm getting lots of these

> SomeFile.ts:46:41 - error TS2694: Namespace '".../node_modules/@types/joi/index"' has no exported member 'extractType'.

(Updated w/ narrowed down issue)

### PR DESCRIPTION
**Pull request by guyellis**

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "joi-extract-type",
-  "version": "0.1.8",
+  "version": "0.2.0",
```
Comment (guyellis) [inline package.json]: @TCMiranda - not sure what you want to do about the versioning as this is a breaking change based on a move to joi 15.x? My suggestion would be to use the Joi version major as the major for this repo. So this would become `15.0.0`. That way multiple major versions can be maintained.

Comment (TCMiranda) [reply package.json]: Hey @guyellis, thank you for the work and the suggestion.
I don't know either but I think it is a common and reasonable approach to version a library based on its dependency.
So can you update it to 15.0.0?

Comment (guyellis) [reply package.json]: @TCMiranda - good idea - I've updated it to 15. Thanks.

**Comment by TCMiranda** [comment]
Just published https://www.npmjs.com/package/joi-extract-type as @15.0.0
Thanks
